### ISSUE TITLE
  Vue template syntax error:

### ISSUE THREAD

**Issue by wwb568109135** [pangz1/vue-ssr#1]
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-56158335!./~/vue-loader/lib/selector.js?type=template&index=0!./front/vue/views/articleDetail.vue

  Vue template syntax error:

  tag <div> has no matching end tag.

webpack: Failed to compile.

**Comment by pangz1** [comment]
在articleDetail.vue 这个文件下面有一个标签没有闭合
